### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by Carlomos7** [aa358/mywebclass-agile-docs#2]
In the branch [MyTheme](https://github.com/aa358/mywebclass-agile-docs/tree/MyTheme), add the following to your google analytics epic as a user story/task:
"[As a website owner, I want to create a Google Analytics account for MyWebClass so that I can track website traffic and user behavior.](https://github.com/Carlomos7/mywebclass-agile-docs/blob/1-feat-my-agile-documentation/documentation/theme_1/initiatives/epics/stories/story_01.md)"

**Comment by aa358** [comment]
Done
