### ISSUE TITLE
Review 5 Adjust milestones

### ISSUE THREAD

**Issue by Carlomos7** [aa358/mywebclass-agile-docs#7]
For your Initiative, "Implement Google Analytics to track website performance and user behavior." adjust your milestones:
- Google Analytics tracking code implemented on website (1 week)
- Custom tracking metrics and dimensions defined and configured (2 weeks)
- Conversion tracking and funnels configured (3 weeks)
- Goals and alerts configured (4 weeks)
- Customized reports configured and available to the team (5 weeks)
- Team trained on how to interpret and use Google Analytics data (6 weeks)

**Comment by aa358** [comment]
Done
